language: node_js
node_js:
- '10'
script: npm run deploy
deploy:
  provider: pages
  repo: jpg0/jpg0.github.io
  skip_cleanup: true
  github_token: $DEPLOY_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: out
